[k8s_servers]
posctl-dev-cp-1 ansible_host=10.10.0.11
posctl-dev-cp-2 ansible_host=10.10.0.12
posctl-dev-cp-3 ansible_host=10.10.0.13

[k8s_workers]
posctl-dev-worker-1 ansible_host=10.10.0.21
posctl-dev-worker-2 ansible_host=10.10.0.22
posctl-dev-worker-3 ansible_host=10.10.0.23

[all:vars]
ansible_user=ubuntu
ansible_python_interpreter=/usr/bin/python3
