apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - networkpolicy.yaml
  - servicemonitor.yaml
  - externalsecret.yaml
configMapGenerator:
  - name: posctl-api-config
    literals:
      - SPRING_PROFILES_ACTIVE=prod
      - OTLP_ENDPOINT=http://tempo.observability:4318/v1/traces
